# Generated by Django 3.2 on 2024-01-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map3d', '0002_alter_supercam_obs_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperCamMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('product_class', models.TextField()),
                ('title', models.TextField()),
                ('version_id', models.TextField()),
            ],
        ),
    ]
