# Generated by Django 3.2 on 2024-01-08 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map3d', '0003_supercammeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='supercammeta',
            name='local_mean_solar_time',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supercammeta',
            name='local_true_solar_time',
            field=models.TextField(default=datetime.datetime(2024, 1, 8, 20, 0, 59, 924166)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supercammeta',
            name='processing_level',
            field=models.TextField(default='example1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supercammeta',
            name='solar_longitude',
            field=models.TextField(default='example'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supercammeta',
            name='solar_longitude_unit',
            field=models.TextField(default='example'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supercammeta',
            name='start_date_time',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supercammeta',
            name='stop_date_time',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
