# Generated by Django 3.2 on 2024-01-18 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map3d', '0004_auto_20240108_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='supercam',
            name='sol',
            field=models.IntegerField(default=16),
            preserve_default=False,
        ),
    ]
