# Generated by Django 3.2 on 2023-11-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_projects_project'),
        ('spectra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='share_project',
            field=models.ManyToManyField(to='accounts.Project'),
        ),
    ]
