# Generated by Django 3.2 on 2023-12-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0002_spectrum_share_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrum',
            name='data_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
