# Generated by Django 3.2 on 2023-12-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0003_alter_spectrum_data_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectrum',
            name='obs_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
