# Generated by Django 3.2 on 2023-12-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spectra', '0004_spectrum_obs_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spectrum',
            name='data_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
