# Generated by Django 3.2 on 2023-11-21 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sections',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='accounts.section'),
        ),
    ]
