# Generated by Django 3.2 on 2023-11-22 08:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('admin', models.ManyToManyField(related_name='project_admin', to=settings.AUTH_USER_MODEL)),
                ('member', models.ManyToManyField(related_name='project_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
