# Generated by Django 3.2 on 2023-11-23 11:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
