# Generated by Django 3.2 on 2023-11-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_projects_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
